### ISSUE TITLE
Missing dependencies fail to compile

### ISSUE THREAD

**Issue by buzai** [renaudjenny/SoliArt#1]
add SwiftUICardGame, but A new error has occurred

SoliArt-bsxlxgplmbqaqgdklcupicplnnhf/SourcePackages/checkouts/swift-ui-card-game/Sources/SwiftUICardGame/StandardDeck/StandardDeckCard.swift:19:29: Function declares an opaque return type, but the return statements in its body do not have matching underlying types

**Comment by renaudjenny** [comment]
Hey @buzai , thanks a lot for your interest about this project.
Indeed, with last commits, this project is not compilable per se.
I'm modifying the `SwiftUICardGame` library in the same time and locally, then it's not possible to compile it without my local modifications.

Knowing you're interesting to compile, I will make an update in both `SwiftUICardGame` and this project to be compilable in the few next hours. I will let you know as soon as it's ready as I need to update two repos.

**Comment by renaudjenny** [comment]
@buzai it should be fixed thanks to b453fd909c8188778a9f50b31e7739d8ee33a7b2 and https://github.com/renaudjenny/swift-ui-card-game/commit/ab0aefd7468322efa52abf42cccc57a8e33575ac

Could you please pull the last changes and retest? Thanks a lot :)

**Comment by buzai** [comment]
@renaudjenny 
Cool, everything is fine now
